$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  sources:
    - 'src/**/*'
  tests:
    - 'tests/**/*'
    - '**/*.test.{ts,tsx}'
    - '**/*.spec.{ts,tsx}'
  configs:
    - '*.config.{ts,js,mjs,cjs}'
    - 'tsconfig.json'
    - 'tsconfig.*.json'

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '@globs(configs)'
      - '/tsconfig.base.json'
